[build]
  publish = "public"
  functions = "netlify/functions"

[dev]
  publish = "public"
  functions = "netlify/functions"
  framework = "#custom"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/index"
  status = 200
